// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRegedit() {
  return window['go']['main']['App']['CheckRegedit']();
}

export function HandleRootDirectorySetOnProgrammStart() {
  return window['go']['main']['App']['HandleRootDirectorySetOnProgrammStart']();
}

export function ReadDirectory(arg1, arg2) {
  return window['go']['main']['App']['ReadDirectory'](arg1, arg2);
}

export function ReadFilesForDocx(arg1, arg2) {
  return window['go']['main']['App']['ReadFilesForDocx'](arg1, arg2);
}

export function SaveWordFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWordFile'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFilesDirectly() {
  return window['go']['main']['App']['SelectFilesDirectly']();
}

export function UpdateRegedit(arg1) {
  return window['go']['main']['App']['UpdateRegedit'](arg1);
}
